# Generated by Django 4.2.4 on 2023-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDiego', '0002_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='horarios_de_atencion',
            field=models.TimeField(),
        ),
    ]
